name: win_ble
description: WinBle Plugin to use Bluetooth Low Energy in Flutter Windows Desktop
version: 0.0.2
homepage: https://github.com/rohitsangwan01/win_ble.git
repository: https://github.com/rohitsangwan01/win_ble.git

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - packages/win_ble/assets/BLEServer.exe
  plugin:
    platforms:
      windows:
        pluginClass: WinBlePlugin
